# European Football Data Analysis with SQL: Manchester United Performance

## How many home and away goals did Manchester United score in each season?

In [ ]:
df_1 = _deepnote_execute_sql('SELECT season,\n       SUM(CASE WHEN hometeam_id = 10260\n		     THEN home_goal END) AS home_goals,\n	   SUM(CASE WHEN awayteam_id = 10260\n		     THEN away_goal END) AS away_goals\nFROM \'match.csv\'\nGROUP BY season;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_1

season  home_goals  away_goals
0  2011/2012        52.0        37.0
1  2012/2013        45.0        41.0
2  2013/2014        29.0        35.0
3  2014/2015        41.0        21.0

In the 2011/2012 season, Manchester United as Home Team scored 52 goals, and as Away Team scored 37 goals. Compared to the seasons of the following years, that was the best and highest-scored home goal.

## How many home and away matches did Manchester United win in each season?

In [ ]:
df_3 = _deepnote_execute_sql('SELECT season, \n       COUNT(CASE WHEN hometeam_id = 10260 AND home_goal > away_goal\n			 THEN id END) AS home_wins,\n	   COUNT(CASE WHEN awayteam_id = 10260 AND away_goal > home_goal\n			 THEN id END) AS away_wins\nFROM \'match.csv\'\nGROUP BY season;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3

season  home_wins  away_wins
0  2011/2012         15         13
1  2012/2013         16         12
2  2013/2014          9         10
3  2014/2015         14          6

For the 2012/2013 season, Manchester United won 16 home matches and 12 away matches. This season was Manchester United's best in terms of home and away wins. Whatever, in the previous season, 2011/2012 won just one match more as away team and one less as home team.

## What is Manchester United's average number of goals per season?

In [ ]:
df_4 = _deepnote_execute_sql('SELECT season,\n       ROUND(AVG(CASE WHEN hometeam_id = 10260\n		        THEN home_goal END),2) AS avg_homegoals,\n	   ROUND(AVG(CASE WHEN awayteam_id = 10260\n				THEN away_goal END),2) AS avg_awaygoals\nFROM \'match.csv\'\nGROUP BY season;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_4

season  avg_homegoals  avg_awaygoals
0  2011/2012           2.74           1.95
1  2012/2013           2.37           2.16
2  2013/2014           1.53           1.84
3  2014/2015           2.16           1.11

For the 2012/2013 season, Manchester United recorded the highest average of goals scored as both home team (2.37 goals) and away team (2.16 goals). This season stood out as the most prolific in terms of goals for Manchester United, both home and away.

## What percentage of Manchester's games did they win in each season?

In [ ]:
df_5 = _deepnote_execute_sql('SELECT season,\n       ROUND(AVG(CASE WHEN hometeam_id = 10260 AND home_goal > away_goal THEN 1\n				      WHEN awayteam_id = 10260 AND home_goal < away_goal THEN 0\n				      END),2) AS pct_homewins,\n	   ROUND(AVG(CASE WHEN awayteam_id = 10260 AND away_goal > home_goal THEN 1\n				      WHEN awayteam_id = 10260 AND away_goal < home_goal THEN 0\n				      END),2) AS pct_awaywins\nFROM \'match.csv\'\nGROUP BY season;\n	                  ', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_5

season  pct_homewins  pct_awaywins
0  2011/2012          0.54          0.81
1  2012/2013          0.57          0.86
2  2013/2014          0.47          0.67
3  2014/2015          0.70          0.55

Overall, the team showed a solid performance both at home and away throughout the seasons analysed. Of particular note was the 2014/2015 season, where Manchester United had a remarkably high winning percentage at home (70%), while their away performance was slightly lower.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c5c689ae-d718-41e9-a35e-60b679021dca' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>